### PR TITLE
Adding a kubetest2 deployer for EC2

### PR DESCRIPTION
**Pull request by dims**
A new `kubetest2-ec2` binary which can be invoked as follows uses `kubeadm` in `cloud-init` to create a single node (for now):

```
kubetest2 ec2 \
 --build \
 --repo-root $HOME/go/src/k8s.io/kubernetes \
 --instance-type=m6a.large  \
 --images=ami-02675d30b814d1daa \
 --region us-east-1 \
 --target-build-arch linux/amd64 \
 --stage dims-aws-test-infra \
 --up \
 --user-data-file=$HOME/go/src/sigs.k8s.io/provider-aws-test-infra/cmd/kubetest2-ec2/config/ubuntu2204.yaml \
 --ssh-user=ec2-user \
 --ssh-env=aws \
 --test=ginkgo \
 -- \
 --use-built-binaries true \
 --focus-regex='\[Conformance\]'
```

### CODE REVIEW

**Comment by dims** [comment]
Raw console output example - https://pastebin.com/raw/NYGcMf5a

**Comment by dims** [comment]
`arm64` works fine as well

```
# ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20230728

kubetest2 ec2 \
 --build \
 --repo-root $HOME/go/src/k8s.io/kubernetes \
 --instance-type=m6g.large  \
 --images=ami-067cf009aedb2612d \
 --region us-east-1 \
 --target-build-arch linux/arm64 \
 --stage dims-aws-test-infra \
 --up \
 --user-data-file=$HOME/go/src/sigs.k8s.io/provider-aws-test-infra/cmd/kubetest2-ec2/config/ubuntu2204.yaml \
 --ssh-user=ec2-user \
 --ssh-env=aws \
 --test=ginkgo \
 -- \
 --use-built-binaries true \
 --focus-regex='\[Conformance\]'
```

Here's evidence :)

```
ec2-user@ip-172-31-44-0:~$ uname -a
Linux ip-172-31-44-0 5.19.0-1029-aws #30~22.04.1-Ubuntu SMP Thu Jul 13 17:21:19 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
ec2-user@ip-172-31-44-0:~$ kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o json | grep arm64
                    "beta.kubernetes.io/arch": "arm64",
                    "kubernetes.io/arch": "arm64",
                            "registry.k8s.io/kube-apiserver-arm64:v1.29.0-alpha.0.40_f4041204c00293",
                            "registry.k8s.io/kube-controller-manager-arm64:v1.29.0-alpha.0.40_f4041204c00293",
                            "registry.k8s.io/kube-proxy-arm64:v1.29.0-alpha.0.40_f4041204c00293",
                            "registry.k8s.io/kube-scheduler-arm64:v1.29.0-alpha.0.40_f4041204c00293",
                            "registry.k8s.io/kubectl-arm64:v1.29.0-alpha.0.40_f4041204c00293",
                    "architecture": "arm64",
```

**Review by tzneal — APPROVED** [review]
/lgtm

**Comment by upodroid** [comment]
On the next iteration, can we launch the worker instances via ASGs?

**Comment by tzneal** [comment]
> On the next iteration, can we launch the worker instances via ASGs?
> 
> That is how the gce cluster tests are ran.

I thought that was an artifact of how GKE worked (e.g. you can't just join a VM to a GKE cluster, it must be part of a node pool).  I'm not super familiar with GCP though, so I could be wrong.

**Comment by upodroid** [comment]
It is not a GKE thing. kops does it and it is the approach for launching identical n+1 instances across zones and regions.


https://cloud.google.com/compute/docs/instance-groups

**Pull request merged**
